// update device token  -- firebase token
export const UPDATE_USER_DEVICE_TOKEN = "/users/deviceToken/addOrRemove/";
export const BASE_URL = 'http://93.188.167.68:6100/api';
export const LOGIN_URL = '/users/login';
export const GET_USER_URL = "/users/getById/";
export const UPDATE_FAVOURITE_SUBCATEGORIES_URL = "/favourites/subCategories";
export const GET_UserGroups_URL = "/categories";
export const UPDATE_USER_URL = "/users/update/";
export const REGISTER_USER_URL = "/users/register";
export const ResetPassword_URL = '/users/resetPassword';
export const AddAddress_URL = '/users/addAddress';
export const AddressList_URL = '/users/addressList/';
export const AddressUpdate_URL = '/users/addressUpdate/'
export const ProductList_URL = '/products/list?'
export const ProductSearch_URL = '/products/search?'
export const ProductCategories_URL = '/products/subCategories'
export const FavouriteProductCategories_URL = '/favourites/subCategories?'
export const GET_Product_BySubCategories_UserGroup_URL = '/products/bySubCategories?'
export const UploadProfilePic_URL = '/users/uploadProfilePic'
export const PlaceOrder_URL = '/orders/placeOrder'
export const OrderList_URL = '/orders/list?'
export const SEND_OTP_URL = '/users/otp'
export const VERIFY_OTP_URL = '/users/otp/verify'
export const FORGOTPASSWORD_URL = '/users/forgotPassword'
export const CREATE_TASKCATEGORIES_URL = "/categories"
export const GET_TASKCATEGORIES_URL = "/categories?"
export const PUT_TASKCATEGORIES_URL = "/categories/"
export const CREATE_TASK_URL = "/tasks"
export const GET_QUOTES_URL = "/quotes"
export const CustomerUserSearch_URL = '/users/search?'
export const GET_PRODUCT_BYSUBCATEGORY_URL = '/subCategories/getByCategory?'
export const PUT_CUSTOMER_USER_URL = "/users/update/"
export const CREATE_CUSTOMER_USER_URL = "/users/register"
export const SEARCH_VENDOR_URL = "/stores/search?"
export const GET_VENDOR_URL = '/favourites/stores'
export const PUT_ADDVENDOR_URL = '/favourites/stores'
export const UPLOADIMAGE_URL = '/uploads/image/'
export const GET_USERLIST_URL = '/users/list?'
export const GET_TASKLIST_URL = '/tasks?'
export const PUT_UPDATE_TASK_BY_STATUS_URL = '/tasks/updateStatus/'
export const DELETE_TASK_URL = '/tasks/delete/'
export const UPDATE_TASK_URL = "/tasks/update/"
export const GET_SEARCH_COMPANY_URL = '/users/searchCompany?'
export const UPDATE_COMPANYDETAIL_URL = '/users/update/companyAdderessList?'
export const GET_ORDERS_BY_STATUS_URL = '/orders/getByStatus?'
export const ORDER_UPDATE_STATUS_URL = '/orders/updateStatus/'
export const SELECTED_CUSTOMER_URL = "/inPersons/selectCustomer/"
export const ADD_CONTACT_INPERSON = "/inPersons/addContact"
export const FREE_TRAIL_PLAN="/payment/freeTrial"
export const GET_FEATURES="/features?"
export const GET_PLAN="/plans?"
export const PAYMENT_PAY_AMOUNT="/payment/payAmount"
export const FACEBOOK_LOGIN = "/users/facebook/login"
export const USER_DETAIL="/users/getById/"
export const PLAN_UNSUBSCRIBE="/payment/unsubscribePlan"
// polices
export const TERM_AND_POLICIES = "http://93.188.167.68:6100/term&policies"
